apiVersion: v1
kind: Pod
metadata:
  name: securitycontext-sysctls-demo
  namespace: default
spec: 
  securityContext:
  - name: kernel.shm_rmid.forced
    value: "0"
  - name: net.ipv4.ip_unprivileged_port_start
    value: "0"
  containers:
  - name: demo
    image: ikubernetes/demoapp:v1.0
    imagePullPolicy: IfNotPresent
    securityContext:
      runAsUser: 1001
      runAsGroup: 1001