apiVersion: v1
kind: Service
metadata:
  name: demo-svc
  namespace: default
spec: 
  type: ClusterIP
  selector:
    app: mypod
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  
